################################################################################
#
# Common Makefile for each test (Please include this file)
#
################################################################################

ifeq ($(origin SYSDEPDIR), undefined)
   SYSDEPDIR = $(TOPDIR)/sysdep
endif

ifeq ($(origin BINNAME), undefined)
   BINNAME = nhm_driver
endif

BUILDDIR     := $(TOPDIR)/.libs
NICAM_BINDIR  = $(TOPDIR)

include $(SYSDEPDIR)/Makedef.$(NICAM_SYS)
include $(TOPDIR)/Mkinclude

all:
	$(MAKE) build
	$(MAKE) tools

build:
	mkdir -p $(BUILDDIR)
	$(MAKE) -C $(TOPDIR)/src nhm NICAM_BINDIR=$(NICAM_BINDIR) \
                                BUILDDIR=$(BUILDDIR)         \
                                SYSDEPDIR=$(SYSDEPDIR)

tools:
	mkdir -p $(BUILDDIR)
	$(MAKE) -C $(TOPDIR)/src BUILDDIR=$(BUILDDIR) \
                            SYSDEPDIR=$(SYSDEPDIR)

run: jobshell
	$(JOBSUB) run.sh

jobshell:
	@if [ -f ../Mkjobshell.$(NICAM_SYS).sh ]; then \
		sh ../Mkjobshell.$(NICAM_SYS).sh $(glevel) $(rlevel) $(nmpi) $(zlayer) $(vgrid) $(TOPDIR) $(BINNAME); \
	else \
		sh $(TOPDIR)/sysdep/Mkjobshell.$(NICAM_SYS).sh $(glevel) $(rlevel) $(nmpi) $(zlayer) $(vgrid) $(TOPDIR) $(BINNAME); \
	fi



.PHONY: allclean clean

allclean:
	$(MAKE) -C $(TOPDIR)/src allclean NICAM_BINDIR=$(NICAM_BINDIR) \
                                     BUILDDIR=$(BUILDDIR)         \
                                     SYSDEPDIR=$(SYSDEPDIR)
	rm -f run.sh

clean:
	$(MAKE) -C $(TOPDIR)/src clean BUILDDIR=$(BUILDDIR) \
                                  SYSDEPDIR=$(SYSDEPDIR)
