################################################################################
#
# Makefile for each test program
#
################################################################################
PWD       = $(shell pwd)
TOPDIR    = $(abspath ../../../..)
TESTDIR   = ../../..


# parameters for run
glevel    = none
rlevel    = none
nmpi      = none
zlayer    = none
vgrid     = none

BINNAME   = mkmnginfo

# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
