################################################################################
#
# Makefile for each test program
#
################################################################################
PWD       = $(shell pwd)
TOPDIR    = $(abspath ../../../..)
TESTDIR   = ../../..


# parameters for run
glevel    = 5
rlevel    = 1
nmpi      = 40
zlayer    = none
vgrid     = none

BINNAME   = fio_ico2ll_mpi

# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
