################################################################################
#
# Makefile for each test program
#
################################################################################
PWD       = $(shell pwd)
TOPDIR    = $(abspath ../../../..)
TESTDIR   = ../../..

# parameters for run
glevel    = 8
rlevel    = 2
nmpi      = 160
zlayer    = 30
vgrid     = vgrid30_stretch_30km_dcmip2016v2.dat



# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
