################################################################################
#
# Makefile for each test program
#
################################################################################
PWD       = $(shell pwd)
TOPDIR    = $(abspath ../../../..)
TESTDIR   = ../../..

# parameters for run
glevel    = 7
rlevel    = 2
nmpi      = 160
zlayer    = 40
vgrid     = vgrid40_600m_24km.dat



# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
