################################################################################
#
# Makefile for each test program
#
################################################################################
PWD       = $(shell pwd)
TOPDIR    = $(abspath ../../../..)
TESTDIR   = ../../..


# parameters for run
glevel    = 6
rlevel    = 0
nmpi      = 10
zlayer    = none
vgrid     = none

BINNAME   = mkhgrid

# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
