################################################################################
#
# Makefile for each test program
#
################################################################################
PWD       = $(shell pwd)
TOPDIR    = $(abspath ../../../..)
TESTDIR   = ../../..
SYSDEPDIR = $(abspath ..)

# parameters for run
glevel    = 5
rlevel    = 0
nmpi      = 10
zlayer    = 40
vgrid     = vgrid40_600m_24km.dat



# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
